### ISSUE TITLE
Emacs 30.0.50 will freeze after pressing `)` when inside a widget's child

### ISSUE THREAD

**Issue by dalugm** [50ways2sayhard/dart-ts-mode#2]
Sample code

`█` means the cursor point.

```dart
ElevatedButton(onPressed: (█)
// Work fine.
ElevatedButton(onPressed: ()█)

Padding(
  padding: const EdgeInsets.all(4.0),
  child: ElevatedButton(onPressed: (█),
)
// Emacs freeze after pressing )
Padding(
  padding: const EdgeInsets.all(4.0),
  child: ElevatedButton(onPressed: ()█),
)
```

It will happen whether `electric-pair-mode` is on or not.

When `electric-pair-mode` is on, Emacs complete the `)` automatically,
then when you press `)`， the expected behavior is that Emacs will skip
`)` and move the cursor to after the `)`, but instead Emacs freezes.

Any ideas what could cause this?

**Comment by 50ways2sayhard** [comment]
Tested on Emacs 29.0.90 and can't reproduce your problem. Emacs works smoothly with your sample, whether `electric-pair-mode` is no or not. Can you provide more details(eg. Emacs version, lsp client, and other related packages)?

**Comment by dalugm** [comment]
> Tested on Emacs 29.0.90 and can't reproduce your problem. Emacs works smoothly with your sample, whether `electric-pair-mode` is no or not. Can you provide more details(eg. Emacs version, lsp client, and other related packages)?

Sorry, I'm using Emacs 30.0.50, compiled from this commit:

https://github.com/emacs-mirror/emacs/commit/c279d65199d

Steps to reproduce:

1. Save the sample code to `test.dart`.
2. `emacs -q -l dart-ts-mode.el test.dart`

**Comment by 50ways2sayhard** [comment]
Thanks I will try it later.

**Comment by 50ways2sayhard** [comment]
It maybe due to the sexp feature introduced in Emacs 30. I temporarily turn off this feature, please upgrade to the latest commit of `main` brunch.

**Comment by dalugm** [comment]
Thanks, after applying the latest patch, it works as I expected.

Should I close this issue or leave it opened?

**Comment by 50ways2sayhard** [comment]
I'll report this issue to Emacs later, any update will be append to this issue.

**Comment by 50ways2sayhard** [comment]
Hey @dalugm ,  I retry your test code with the latest `tree-sitter-dart` and https://github.com/emacs-mirror/emacs/commit/6f940c6a1183dd1660f35e6c82d33183a6892cb4, it seems that your issue was fixed by upstream and Emacs works smoothly. 

Maybe it's related to https://github.com/UserNobody14/tree-sitter-dart/issues/40.

Please uncomment https://github.com/50ways2sayhard/dart-ts-mode/blob/9ea3008cf99c480a1e46dc4e4f28e4a5727ba4de/dart-ts-mode.el#L406 and check with the environment above if it is fixed in your machine :).

**Comment by dalugm** [comment]
> check with the environment above if it is fixed in your machine :).

Sorry for the delayed reply, I havn't check my email these days.

After uncomment the sexp lines, it worked fine with my machine. 

But I met a electric-pair's auto-pair problem, can be reproduced by `emacs -q`:

```dart
Padding(
  padding: const EdgeInsets.all(4.0),
  child: ElevatedButton(onPressed: (█)),
)

// Expected: after pressing ), cursor skips the right )
Padding(
  padding: const EdgeInsets.all(4.0),
  child: ElevatedButton(onPressed: ()█),
)

// Actual: after pressing ), it inserts a )
Padding(
  padding: const EdgeInsets.all(4.0),
  child: ElevatedButton(onPressed: ()█),
)
```

---
Never mind, I retested and didn't meet the above problem. I think it's
ok to uncomment the sexp code now.
