### ISSUE TITLE
Code Formatting - Apheleia Integration

### ISSUE THREAD

**Issue by yassernasc** [50ways2sayhard/dart-ts-mode#3]
I'm using Emacs 30.0.50,

I'm using Apheleia for format the buffer on save, so, inside my `.emacs.d/elpa/apheleia../apheleia-formatters.el` file I added the line:

```elisp
    ...
    (dart-mode . dart-format)
    (dart-ts-mode . dart-format)
    ...
```
I ensured that with `dart-mode` from MELPA it works, I know that probably the problem is not with the `dart-ts-mode` code but I'm here more asking for help than a bug fix. if that's the case, maybe this issue help other users in the future as well.

And thanks for publishing the mode :)

**Comment by 50ways2sayhard** [comment]
Here is my Apheleia config:

```dart
(use-package apheleia
  :commands (apheleia-format-buffer)
  :bind ("C-c c f" . apheleia-format-buffer)
  :init
  (require 'apheleia-formatters)
  (add-to-list 'apheleia-mode-alist '(dart-ts-mode . dart-format))
  (add-to-list 'apheleia-mode-alist '(emacs-lisp-mode . lisp-indent)))
```

I'll add some guide about working with other package inside README later. Thank you for the issue :)

**Comment by 50ways2sayhard** [comment]
To integrate with newest [apheleia](https://github.com/radian-software/apheleia/commit/e9e595f003605a7e366776c7a1715dc7093e29d5), just following line to `:config` part of your apheleia config:
```emacs-lisp
(add-to-list 'apheleia-mode-alist '(dart-ts-mode . dart-format))
```
Full configuration:
```emacs-lisp
(use-package apheleia
  :commands (apheleia-format-buffer)
  :bind ("C-c c f" . apheleia-format-buffer)
  :config
  (add-to-list 'apheleia-mode-alist '(dart-ts-mode . dart-format)))
```
